# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bc92d31b243e9c1234f9d33cc4fce76d439dbb7e932ad2900cf3e9ae77565d382ad1deb7a7a5a394ef2ee42b27c9a8e47e0dbd937bb4eab9cf8147b2b9c3b77

test:
  secret_key_base: 469fbecdf70d61511a38cbddd9427c631e52aa2491f43ae564518f18cd8e37f651690267fbf0407dca5ac06f621a755c7221d2454c30f573102b7a5fec8868da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
